apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default  
spec:
  replicas: 1
  selector:
     matchLabels:
        app: webapp
  template:
     metadata:
       labels: 
         app: webapp
     spec:
       containers:
         - image: kabrajii/ansible-dockerized-app-on-k8s:latest
           name: webapp-deploy
           ports:
           - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
   name: webapp-svc
   namespace: default
spec:
   selector:
       app: webapp
   ports:
   - port: 80
     targetPort: 5000
     protocol: TCP
   type: NodePort
